version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: deployment/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PORT=8000
    volumes:
      - ../app:/app/app
      - ../model:/app/model
      - ../data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: ../deployment/frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped

networks:
  default:
    name: turtil-network 